In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [19]:
columns = ('user_id','movie_id','movie_rating')
dataset = pd.read_csv('ml-100k/u.data', names=columns, sep='\t', usecols=range(3))

dataset.head()

user_id  movie_id  movie_rating
0        0        50             5
1        0       172             5
2        0       133             1
3      196       242             3
4      186       302             3

In [28]:
# Groupby every movie by movie_id
groupedMovies = dataset.groupby('movie_id').agg({'movie_rating':[np.size, np.mean]})
groupedMovies.head()

movie_rating          
                 size      mean
movie_id                       
1                 452  3.878319
2                 131  3.206107
3                  90  3.033333
4                 209  3.550239
5                  86  3.302326

In [33]:
movieNumRatings = pd.DataFrame(groupedMovies['movie_rating']['size'])
moviePopularity = movieNumRatings.apply(lambda x: (x - np.min(x)) / (np.max(x)-np.min(x)))
moviePopularity.head()

size
movie_id          
1         0.773585
2         0.222985
3         0.152659
4         0.356775
5         0.145798

In [52]:
movieDict = {}

with open('ml-100k/u.item') as f:
    temp = ''
    for line in f:
        fields = line.rstrip('\n').split('|')
        movieId = int(fields[0])
        name = fields[1]
        genres = fields[5:25]
        #genres_conv = map(int, genres)
        genres_conv = np.array(genres, dtype=int)
        #print(genres_conv)
        movieDict[movieId] = (name, genres_conv, moviePopularity.loc[movieId].get('size'), groupedMovies.loc[movieId].movie_rating.get('mean'))

[0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
[0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0]
[0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0]
[0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [50]:
print(movieDict[1])

('Toy Story (1995)', array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 0.77358490566037741, 3.8783185840707963)


In [69]:
# let's define a function that computes the "distance"
# between two movies based on how similar their genres are, and how similar their
# popularity is. Just to make sure it works, we'll compute the distance between movie ID's 2 and 4:

from scipy import spatial

def calculateDistance(a,b):
    genresA = a[1]
    genresB = b[1]
    genreDistance = spatial.distance.cosine(genresA, genresB)
    popularityA = a[2]
    popularityB = b[2]
    popularityDistance = abs(popularityA - popularityB)
    return genreDistance + popularityDistance

calculateDistance(movieDict[2], movieDict[4])

0.8004574042309891

In [54]:
print(movieDict[2])
print(movieDict[4])

('GoldenEye (1995)', array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]), 0.22298456260720412, 3.2061068702290076)
('Get Shorty (1995)', array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 0.35677530017152659, 3.5502392344497609)
